--- #YAML:1.0
name:               File-Tail-Dir
version:            0.14
abstract:           Tail all matching files in a given set of directories
author:
    - Jon Schutz <jon at jschutz.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config:               0
    Cwd:                  0
    Digest::MD5:          0
    File::ChangeNotify:   0
    File::Spec:           0
    File::Temp:           0
    Moose:                0
    Moose::Util::TypeConstraints:  0
    POSIX:                0
    Test::More:           0
    Time::HiRes:          0
    YAML::Any:            0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
