--- #YAML:1.0
name:                File-Tail-Dir
version:             0.10
abstract:            Tail all matching files in a given set of directories
license:             perl
author:              
    - Jon Schutz <jon at jschutz.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Cwd:                           0
    Digest::MD5:                   0
    File::ChangeNotify:            0
    File::Spec:                    0
    File::Temp:                    0
    Moose:                         0
    Test::More:                    0
    YAML::Any:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
